language: python
python: 2.7

env:
    - OMV_ENGINE=Brian

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all
    - pwd
    - ls -alt
    - ls -alt Brian/results
    
    
    

